# Generated by Django 2.2.5 on 2019-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='expiry_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockin',
            name='manufacturing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
