# Generated by Django 2.2.5 on 2019-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190906_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='cost',
            new_name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='total',
        ),
        migrations.AddField(
            model_name='stockin',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
