# Generated by Django 2.2.5 on 2019-09-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190906_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbalance',
            old_name='product',
            new_name='product_item',
        ),
        migrations.RenameField(
            model_name='stockin',
            old_name='product',
            new_name='product_item',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='product',
            new_name='product_item',
        ),
    ]
