# Generated by Django 2.2.5 on 2019-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190906_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbalance',
            old_name='cost',
            new_name='cost_per_unit',
        ),
        migrations.RenameField(
            model_name='stockout',
            old_name='cost',
            new_name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='stockbalance',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='tax',
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockin',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='out_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stockout',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
    ]
