# Generated by Django 2.2.5 on 2019-09-06 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20190906_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbalance',
            name='total',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='total',
        ),
        migrations.AlterField(
            model_name='stockin',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='manufacturing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='out_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
